name: 250512_RNA-seq_tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.15.0
  - freetype=2.13.3
  - hisat2=2.2.1
  - htslib=1.21
  - krb5=1.21.3
  - libasprintf=0.24.1
  - libcurl=8.13.0
  - libcxx=20.1.4
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.24.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libintl=0.24.1
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libunistring=0.9.10
  - libzlib=1.3.1
  - ncurses=6.5
  - openjdk=23.0.2
  - openssl=3.5.0
  - perl=5.32.1
  - pip=25.1.1
  - python=3.13.3
  - python_abi=3.13
  - readline=8.2
  - samtools=1.21
  - subread=2.1.1
  - tk=8.6.13
  - trimmomatic=0.39
  - tzdata=2025b
  - wget=1.21.4
  - zlib=1.3.1
  - zstd=1.5.7
